<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="187327" started-at="2020-05-18T23:07:41 IST" finished-at="2020-05-18T23:10:48 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="187327" started-at="2020-05-18T23:07:41 IST" finished-at="2020-05-18T23:10:48 IST">
      <class name="TestCases.Loginwithdatabase">
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="5003" started-at="2020-05-18T23:07:43 IST" finished-at="2020-05-18T23:07:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="13293" started-at="2020-05-18T23:07:48 IST" data-provider="DP" finished-at="2020-05-18T23:08:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lp@absms4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="150" started-at="2020-05-18T23:08:01 IST" finished-at="2020-05-18T23:08:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3356" started-at="2020-05-18T23:08:02 IST" finished-at="2020-05-18T23:08:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="12523" started-at="2020-05-18T23:08:05 IST" data-provider="DP" finished-at="2020-05-18T23:08:17 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lp@absms4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Loginwithdatabase.login(Loginwithdatabase.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="98" started-at="2020-05-18T23:08:17 IST" finished-at="2020-05-18T23:08:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3499" started-at="2020-05-18T23:08:18 IST" finished-at="2020-05-18T23:08:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="16742" started-at="2020-05-18T23:08:21 IST" data-provider="DP" finished-at="2020-05-18T23:08:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl@ymail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lp@absms4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Loginwithdatabase.login(Loginwithdatabase.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="82" started-at="2020-05-18T23:08:38 IST" finished-at="2020-05-18T23:08:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3687" started-at="2020-05-18T23:08:38 IST" finished-at="2020-05-18T23:08:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="14323" started-at="2020-05-18T23:08:42 IST" data-provider="DP" finished-at="2020-05-18T23:08:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl@redmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lp@absms4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Loginwithdatabase.login(Loginwithdatabase.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="701" started-at="2020-05-18T23:08:56 IST" finished-at="2020-05-18T23:08:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="38191" started-at="2020-05-18T23:08:57 IST" finished-at="2020-05-18T23:09:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="12906" started-at="2020-05-18T23:09:35 IST" data-provider="DP" finished-at="2020-05-18T23:09:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl@smail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lp@absms4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.Loginwithdatabase.login(Loginwithdatabase.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="101" started-at="2020-05-18T23:09:48 IST" finished-at="2020-05-18T23:09:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3562" started-at="2020-05-18T23:09:48 IST" finished-at="2020-05-18T23:09:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="13625" started-at="2020-05-18T23:09:51 IST" data-provider="DP" finished-at="2020-05-18T23:10:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vs56@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qw2020@may]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="112" started-at="2020-05-18T23:10:05 IST" finished-at="2020-05-18T23:10:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3517" started-at="2020-05-18T23:10:05 IST" finished-at="2020-05-18T23:10:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="22264" started-at="2020-05-18T23:10:09 IST" data-provider="DP" finished-at="2020-05-18T23:10:31 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[sl56@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[as2020@may]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="255" started-at="2020-05-18T23:10:31 IST" finished-at="2020-05-18T23:10:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="initialize" is-config="true" duration-ms="3480" started-at="2020-05-18T23:10:31 IST" finished-at="2020-05-18T23:10:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="login(java.lang.String, java.lang.String)[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="login" duration-ms="12525" started-at="2020-05-18T23:10:35 IST" data-provider="DP" finished-at="2020-05-18T23:10:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[vsl56@hotmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[zx@gmail.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="close()[pri:0, instance:TestCases.Loginwithdatabase@3fd7a715]" name="close" is-config="true" duration-ms="1221" started-at="2020-05-18T23:10:47 IST" finished-at="2020-05-18T23:10:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- TestCases.Loginwithdatabase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
